server:
  port: 8000
spring:
  application:
    name: itcast-health-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.81:3306/itcast_health?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 192.168.31.81
    port: 6379
mybatis:
  type-aliases-package: cn.itcast.pojo
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
dubbo:
  application:
    name: itcast-health-service
  registry:
    address: zookeeper://192.168.31.81:2181
    client: zkclient
    timeout: 60000
  consumer:
    timeout: 60000
  scan:
    base-packages: cn.itcast
  protocol:
    port: 20890
pay:
  wxpay:
    native:
      appID: wx8397f8696b538317
      mchID: 1473426802
      key: T6m9iK73b0kn9g5***MKfHQH7X8rKwb
      payNotifyUrl: http://a31ef7db.ngrok.io/WeChatPay/WeChatPayNotify
