server:
  port: 9000
spring:
  application:
    name: itcast-health-backend
  redis:
    host: 192.168.31.81
    port: 6379
dubbo:
  application:
    name: itcast-health-backend
  registry:
    address: zookeeper://192.168.31.81:2181
    client: zkclient
    timeout: 60000
  consumer:
    timeout: 60000
  scan:
    base-packages: cn.itcast
